AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: >
  TODO-LIST v5.0 

Globals:
  Function:
    Timeout: 3
    MemorySize: 128

Resources:
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: develop

  MyApiGetFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: \backend\lambda
      Handler: lambda_function.lambda_handler
      Runtime: python3.10
      Architectures:
        - x86_64
      Role: arn:aws:iam::875625547240:role/fullstack-s3-lambda-access
      FunctionName: 
      Events:
        Getapp:
          Type: HttpApi
          Properties:
            Path: /
            Method: GET
            ApiId:
              Ref: HttpApi





































# AWSTemplateFormatVersion: '2010-09-09'
# Transform: AWS::Serverless-2016-10-31


# Resources:
#   RestApi:
#     Type: AWS::Serverless::Api
#     Properties:
#       StageName: prod

#   ItemTable:
#     Type: AWS::DynamoDB::Table
#     Properties:
#       TableName: newTable
#       AttributeDefinitions:
#         - AttributeName: ID
#           AttributeType: S
#       KeySchema:
#         - AttributeName: ID
#           KeyType: HASH
#       ProvisionedThroughput:
#         ReadCapacityUnits: 5
#         WriteCapacityUnits: 5

#   LambdaFunction:
#     Type: AWS::Serverless::Function
#     Properties:
#       Handler: lambda_function.lambda_handler
#       Role: arn:aws:iam::875625547240:role/fullstack-s3-lambda-access
#       FunctionName: lambda_function
#       CodeUri: ./
#       Runtime: python3.10
#       Environment:
#         Variables:
#           DYNAMODB_TABLE: !Ref ItemTable
#       Events:
#         ApiEvent:
#           Type: Api
#           Properties:
#             Path: /items/{id}
#             Method: ANY

# # Outputs:
# #   ApiURL:
# #     Description: URL of the API Gateway
# #     Value: !Sub "https://${RestApi}.execute-api.${AWS::Region}.amazonaws.com/prod/"
